### ISSUE TITLE
MSGraphClientModels repo has been archived, is it deprecated?

### ISSUE THREAD

**Issue by luisangelsm** [microsoftgraph/msgraph-sample-ios-swift#16]
This project uses `MSGraphClientModels` as a dependency, but https://github.com/microsoftgraph/msgraph-sdk-objc-models has been archived, is there a replacement for it?

**Comment by gkamenov11** [comment]
Facing the same issue.

**Comment by jasonjoh** [comment]
No, unfortunately there is not a replacement for it. A Swift-based replacement is being looked into, but I have no timelines to share.
